<?php

return [
    'dashboard' => [
        'title' => 'Dashboard',
        'operational_dashboard' => 'Operational Dashboard',
        'realtime_monitoring' => 'Real-time metrics and activity monitoring',
        
        'stats' => [
            'total_models' => 'Total Models',
            'models' => 'Models',
            'total_fans' => 'Total Fans',
            'fans' => 'Fans',
            'live_now' => 'Live Now',
            'subscriptions' => 'Subscriptions',
            'total_revenue' => 'Total Revenue',
            'global_platform' => 'Global Platform',
            'this_month' => 'this month',
            'pending_review' => 'Pending Review',
            'quick_access' => 'Quick Access',
        ],

        'recent_streams' => [
            'title' => 'Recent Streams',
            'view_all' => 'View All',
            'model' => 'Model',
            'status' => 'Status',
            'viewers' => 'Viewers',
            'start' => 'Start',
            'live' => 'Live',
            'ended' => 'Ended',
            'na' => 'N/A',
            'no_activity' => 'No streaming activity currently',
        ],

        'content' => [
            'photos' => 'Photos',
            'videos' => 'Videos',
        ],

        'quick_links' => [
            'admin' => 'Admin',
            'models' => 'Models',
            'verification' => 'Verif.',
            'settings' => 'Settings',
        ],
    ],

    'analytics' => [
        'title' => 'Analytics',
        'dashboard_title' => 'Analytics Dashboard',
        'subtitle' => 'Intelligent visualization of critical metrics and ecosystem performance',
        
        'overview' => [
            'total_community' => 'Total Community',
            'active_fans' => 'Active Fans',
            'registered_models' => 'Registered Models',
            'tokens_moved' => 'Tokens Moved',
            'live_now' => 'Live Now',
            'vs_previous_month' => 'vs previous month',
            'real_time' => 'Real-time',
        ],

        'charts' => [
            'revenue_trend' => 'Revenue Trend',
            'live_data' => 'LIVE DATA',
            'revenue_subtitle' => 'Comparative analysis of the last 12 months of operation',
            'real_time_viz' => 'Real-time Data Visualization',
            'projected_total' => 'Projected total:',
            'tokens' => 'tokens',
        ],

        'metrics' => [
            'user_engagement' => 'User Engagement',
            'engagement_subtitle' => 'Audience behavior and retention',
            'avg_session' => 'Avg Session Duration',
            'avg_concurrency' => 'Avg Concurrency',
            'viewers' => 'viewers',
            'tip_volume' => 'Tip Volume',
            'tips' => 'tips',
            'sub_conversion' => 'Sub Conversion',
            'users' => 'users',

            'content_inventory' => 'Content Inventory',
            'inventory_subtitle' => 'Volume of media generated by creators',
            'published_photos' => 'Published Photos',
            'published_videos' => 'Published Videos',
            'live_broadcasts' => 'Total Live Broadcasts',
            'pending_moderation' => 'Pending Moderation',
            'items' => 'items',
        ],

        'top_models' => [
            'title' => 'Elite Performers (Top Models)',
            'subtitle' => 'Model ranking by accumulated tokens',
            'rank' => 'Rank',
            'model' => 'Model',
            'contact' => 'Contact',
            'accumulated_tokens' => 'Accumulated Tokens',
            'no_data' => 'No performance data available.',
        ],
    ],

    'content' => [
        'photos' => [
            'title' => 'Photo Moderation',
            'subtitle' => 'Review and approve visual content from creators',
            'total' => 'Total Photos',
            'no_photos_title' => 'No photos around here',
            'no_photos_desc' => 'Great job! No photos found matching the filters.',
            'info' => 'Information',
            'meta' => 'Metadata',
            'views' => 'Views',
            'uploaded' => 'Uploaded',
            'file_size' => 'File Size',
        ],
        'videos' => [
            'title' => 'Video Moderation',
            'subtitle' => 'Manage and approve video productions from creators',
            'total' => 'Total Videos',
            'no_videos_title' => 'No pending videos',
            'no_videos_desc' => 'No videos found for moderation matching the filters.',
            'delete_confirm' => 'Permanently delete this video?',
        ],
        'status' => [
            'pending' => 'Pending',
            'approved' => 'Approved',
            'rejected' => 'Rejected',
            'approved_masc' => 'Approved',
            'rejected_masc' => 'Rejected',
            'single_pending' => 'Pending',
            'single_approved' => 'Approved',
            'single_rejected' => 'Rejected',
            'single_approved_masc' => 'Approved',
            'single_rejected_masc' => 'Rejected',
        ],
        'filters' => [
            'all' => 'All',
            'all_masc' => 'All',
            'filter_by_model' => 'Filter by model...',
            'search_by_title' => 'Search by title...',
            'filter_btn' => 'Filter',
            'clear_filters' => 'Clear filters',
        ],
        'actions' => [
            'select_all' => 'Select All',
            'selected' => 'selected',
            'approve_selection' => 'Approve Selection',
            'reject_selection' => 'Reject Selection',
            'approve' => 'Approve',
            'reject' => 'Reject',
            'view' => 'View Video',
            'delete' => 'Delete',
        ],
        'misc' => [
            'untitled' => 'Untitled',
        ],
    ],

    'finance' => [
        'balance' => [
            'title' => 'Financial Balance',
            'subtitle' => 'Platform financial status — income, payouts and net profit.',
            'token_rate' => '1 Token = :value USD',
            'total_income' => 'Total Income',
            'tokens_sold' => 'tokens sold',
            'model_payouts' => 'Model Payouts',
            'payouts_desc' => 'Completed and processed withdrawals',
            'net_profit' => 'Net Profit',
            'profit_desc' => 'Income minus payouts',
            'stats' => [
                'tokens_sold_title' => 'Tokens Sold',
                'tokens_sold_sub' => 'Accumulated purchases',
                'in_circulation' => 'In Circulation',
                'pending_withdrawals' => 'Pending Withdrawals',
                'pending_withdrawals_sub' => 'tokens',
                'active_subscriptions' => 'Active Subscriptions',
                'completed_tips' => 'Completed Tips',
            ],
            'monthly' => [
                'income' => 'Income This Month',
                'payouts' => 'Payouts This Month',
                'profit' => 'Profit This Month',
            ],
            'tables' => [
                'recent_tips' => 'Recent Tips',
                'view_all' => 'View all',
                'sender' => 'Sender',
                'tokens' => 'Tokens',
                'status' => 'Status',
                'date' => 'Date',
                'recent_subs' => 'Recent Subscriptions',
                'subscriber' => 'Subscriber',
                'no_activity' => 'No activity',
            ]
        ],
        'subscriptions' => [
            'title' => 'Subscriptions',
            'subtitle' => 'Manage recurring revenue and membership status.',
            'stats' => [
                'total_charged' => 'Total Tokens Charged',
                'total_charged_sub' => 'Historical accumulated',
                'active_tokens' => 'Active Tokens',
                'active_tokens_sub' => 'In active subscriptions',
                'monthly_tokens' => 'Tokens This Month',
                'cancelled' => 'Cancelled',
                'cancelled_sub' => 'Lost retention',
            ],
            'filters' => [
                'all' => 'All',
                'active' => 'Active',
                'cancelled' => 'Cancelled',
                'expired' => 'Expired',
                'search' => 'Search...',
            ],
            'table' => [
                'subscriber' => 'Subscriber (Fan)',
                'model' => 'Model (Creator)',
                'cost' => 'Cost (Tokens)',
                'status' => 'Status',
                'dates' => 'Start / Renewal',
                'actions' => 'Actions',
                'deleted_user' => 'Deleted User',
                'deleted_model' => 'Deleted Model',
                'renews' => 'Renews:',
                'view_details' => 'View Details',
                'no_subs' => 'No subscriptions registered.',
            ],
            'modal' => [
                'title' => 'Subscription Detail',
                'fan' => 'Fan Subscriber',
                'model' => 'Subscribed Model',
                'current_plan' => 'Current Plan',
                'monthly' => 'Monthly',
                'cost' => 'Cost (Tokens)',
                'status' => 'Status',
                'close' => 'Close',
            ]
        ],
        'tips' => [
            'title' => 'Tips Center',
            'subtitle' => 'Monitor gestures of gratitude and direct transactions between users',
            'stats' => [
                'total_tokens' => 'Tokens in Tips',
                'total_tokens_sub' => 'Historical accumulated',
                'avg_tokens' => 'Average per Tip',
                'avg_tokens_sub' => 'Average tokens',
                'monthly_tokens' => 'Tokens This Month',
                'completed' => 'Completed',
                'pending' => 'Pending',
            ],
            'filters' => [
                'all' => 'All',
                'completed' => 'Completed',
                'pending' => 'Pending',
                'failed' => 'Failed',
                'search' => 'Search user or model...',
            ],
            'table' => [
                'sender' => 'Sender (Fan)',
                'receiver' => 'Receiver (Model)',
                'tokens' => 'Tokens',
                'status' => 'Status',
                'date' => 'Date',
                'actions' => 'Actions',
                'deleted_user' => 'Deleted User',
                'deleted_model' => 'Deleted Model',
                'fan_role' => 'Fan',
                'model_role' => 'Model',
                'view_details' => 'View Details',
                'no_tips' => 'No tips registered.',
            ],
            'modal' => [
                'title' => 'Transaction Detail',
                'tokens_sent' => 'Tokens Sent',
                'tx_id' => 'Transaction ID',
                'date' => 'Date',
                'message' => 'Attached Message',
                'no_message' => 'No message',
                'from' => 'From (Fan)',
                'to' => 'To (Model)',
                'close' => 'Close',
            ]
        ],
    ],

    'gamification-2' => [
        'achievements' => [
            'index' => [
                'title' => 'Manage Achievements',
                'title_header' => 'Achievements',
                'subtitle' => 'Manage rewards and challenges to gamify the user experience.',
                'create_btn' => 'New Achievement',
                'filters' => [
                    'all' => 'All',
                    'active' => 'Active',
                    'inactive' => 'Inactive',
                    'for_models' => 'For Models',
                    'for_fans' => 'For Fans',
                ],
                'table' => [
                    'icon' => 'Icon',
                    'achievement' => 'Achievement',
                    'description' => 'Description',
                    'type_role' => 'Type / Role',
                    'reward' => 'Reward',
                    'status' => 'Status',
                    'actions' => 'Actions',
                    'active' => 'Active',
                    'inactive' => 'Inactive',
                    'edit' => 'Edit',
                    'delete' => 'Delete',
                    'no_achievements' => 'No registered missions found.',
                ],
                'delete_alert' => [
                    'title' => 'Delete this achievement?',
                    'text' => 'This action cannot be undone.',
                    'confirm' => 'Yes, delete',
                    'cancel' => 'Cancel',
                ]
            ],
            'create' => [
                'title' => 'Create Achievement',
                'subtitle' => 'Configure a new recognition and milestones for the community.',
            ],
            'edit' => [
                'title' => 'Edit Achievement',
                'subtitle' => 'Modifying parameters for: ":name"',
            ],
            'form' => [
                'basic_info' => 'Basic Information',
                'name' => 'Name',
                'name_placeholder' => 'Ex: Super Star',
                'slug' => 'Slug (Identifier)',
                'slug_placeholder' => 'ex: super-star',
                'description' => 'Description',
                'description_placeholder' => 'Describe what the user must do to get this achievement...',
                'visualization' => 'Visualization',
                'icon' => 'Icon',
                'icon_placeholder' => 'fa-trophy',
                'rarity' => 'Rarity',
                'rarities' => [
                    'common' => 'Common (Gray)',
                    'rare' => 'Rare (Blue)',
                    'epic' => 'Epic (Purple)',
                    'legendary' => 'Legendary (Gold)',
                ],
                'category' => 'Category',
                'categories_list' => [
                    'content' => 'Content',
                    'earnings' => 'Earnings',
                    'popularity' => 'Popularity',
                    'special' => 'Special',
                ],
                'rewards_rules' => 'Rewards and Rules',
                'role_recipient' => 'Recipient Role',
                'roles' => [
                    'fan' => 'Fans',
                    'model' => 'Models',
                    'both' => 'Both',
                ],
                'status' => 'Status',
                'statuses' => [
                    'active' => 'Active',
                    'inactive' => 'Inactive',
                ],
                'xp' => 'XP (Experience)',
                'tickets' => 'Tickets (Currency)',
                'tickets_edit' => 'Tickets',
                'cancel' => 'Cancel',
                'submit_create' => 'Create Achievement',
                'submit_edit' => 'Save Changes',
            ],
            'guide' => [
                'title' => 'Quick Guide',
                'description' => 'Use this reference to properly configure the missions.',
                'category' => 'Category',
                'category_desc' => 'Defines in which section of the profile the achievement will appear.',
                'rarity' => 'Rarity',
                'rarity_desc' => 'Determines the border color and the glow of the card.',
                'slug' => 'Slug',
                'slug_desc' => 'Must be unique and in \'kebab-case\' format (e.g., first-login).',
                'stats_title' => 'Statistics',
                'stats_desc' => 'Non-editable information.',
                'created_at' => 'Created:',
            ],
        ],
        'levels' => [
            'index' => [
                'title' => 'Levels Management',
                'title_header' => 'Gamification Levels',
                'subtitle' => 'Manage the progression structure, experience, and rewards for the models.',
                'create_button' => 'Add New Level',
                'table' => [
                    'level' => 'Level',
                    'name_league' => 'Name / League',
                    'xp_required' => 'Required XP',
                    'rewards' => 'Rewards',
                    'actions' => 'Actions',
                    'standard' => 'Standard',
                    'no_tokens' => 'No tokens',
                    'tokens' => 'Tokens',
                    'edit' => 'Edit',
                    'delete' => 'Delete',
                ],
                'empty' => [
                    'title' => 'There are no configured levels',
                    'subtitle' => 'Start by creating the first level for your gamification system.',
                    'action' => 'Create First Level',
                ],
                'delete_alert' => [
                    'title' => 'Delete this level?',
                    'text' => 'This action cannot be undone.',
                    'confirm' => 'Yes, delete',
                    'cancel' => 'Cancel',
                ]
            ],
            'create' => [
                'title' => 'New Level',
                'subtitle' => 'Define the name, level number, and progression requirements',
            ],
            'edit' => [
                'title' => 'Edit Level',
            ],
            'form' => [
                'basic_config' => 'Basic Configuration',
                'name' => 'Level Name (League)',
                'name_placeholder' => 'Ex: Green League - Novice',
                'name_helper' => 'Recommended: Include \'League [Color]\' for medal assignment.',
                'level_number' => 'Level Number',
                'xp_required' => 'Required XP',
                'role_recipient' => 'Recipient Role',
                'roles' => [
                    'both' => 'Both (Fan and Model)',
                    'fan' => 'Fan Only',
                    'model' => 'Model Only',
                ],
                'role_helper' => 'The system will use this filter to assign the level to the correct user.',
                'image' => 'Level Image',
                'image_current' => 'Current image',
                'image_preview' => 'Preview',
                'image_helper' => 'JPG, PNG, or WebP. Max 2MB. Recommended: 200x200px.',
                'rewards_section' => 'Rewards on Reaching Level',
                'bonus_tokens' => 'Bonus Tokens',
                'tokens_helper' => 'Tokens automatically granted upon reaching this level.',
                'achievements' => 'Achievements to Grant (Optional)',
                'no_achievements' => 'No active achievements available.',
                'achievements_helper' => 'Will be automatically granted to the user when they reach this level.',
                'badges' => 'Badges to Grant (Optional)',
                'no_badges' => 'No active badges available.',
                'badges_helper' => 'Will be automatically granted to the user when they reach this level.',
                'cancel' => 'Cancel',
                'submit_create' => 'Create Level',
                'submit_edit' => 'Save Changes',
            ],
        ],
        'missions' => [
            'index' => [
                'title' => 'Manage Missions',
                'subtitle' => 'Configure missions and challenges to encourage participation on the platform',
                'stats' => [
                    'total' => 'Total Missions',
                    'active' => 'Active',
                    'weekly' => 'Weekly',
                ],
                'search_placeholder' => 'Search by name...',
                'create_button' => 'New Mission',
                'table' => [
                    'mission' => 'Mission',
                    'type' => 'Type',
                    'goal' => 'Goal',
                    'rewards' => 'Rewards',
                    'status' => 'Status',
                    'actions' => 'Actions',
                    'active' => 'Active',
                    'inactive' => 'Inactive',
                    'edit' => 'Edit',
                    'delete' => 'Delete',
                ],
                'empty' => [
                    'title' => 'No missions',
                    'subtitle' => 'You haven\'t created any missions yet, or none match your search.',
                ],
                'delete_alert' => [
                    'title' => 'Delete this mission?',
                    'text' => 'This action cannot be undone.',
                    'confirm' => 'Yes, delete',
                    'cancel' => 'Cancel',
                ]
            ],
            'create' => [
                'title' => 'New Mission',
                'subtitle' => 'Define the goals and rewards for a new mission',
            ],
            'edit' => [
                'title' => 'Edit Mission',
            ],
            'form' => [
                'basic_config' => 'Basic Configuration',
                'name' => 'Mission Name *',
                'name_placeholder' => 'Ex: Loyal Viewer',
                'description' => 'Description',
                'description_placeholder' => 'Briefly describe what this mission is about...',
                'type' => 'Mission Type *',
                'types' => [
                    'weekly' => 'Weekly (WEEKLY)',
                    'level_up' => 'Level Up (LEVEL_UP)',
                    'parallel' => 'Parallel (PARALLEL)',
                ],
                'role_target' => 'Target Role *',
                'roles' => [
                    'both' => 'Both (Fan and Model)',
                    'fan' => 'Fan Only',
                    'model' => 'Model Only',
                ],
                'required_level' => 'Required Level',
                'no_level' => '-- None (For everyone) --',
                'level_prefix' => 'Level',
                'is_active' => 'Active Mission',
                'goals_section' => 'Goals and Objectives',
                'target_action' => 'Target Action *',
                'target_action_placeholder' => 'Ex: stream_watched',
                'target_action_helper' => 'Internal identifier for the action (slug).',
                'goal_amount' => 'Required Amount *',
                'rewards_section' => 'Rewards on Completion',
                'reward_xp' => 'Experience (XP) *',
                'reward_tickets' => 'Tickets *',
                'achievement' => 'Achievement to Grant (Optional)',
                'no_achievement' => '— No linked achievement —',
                'achievement_helper' => 'The achievement will be unlocked automatically upon completing this mission.',
                'badge' => 'Badge to Grant (Optional)',
                'no_badge' => '— No linked badge —',
                'badge_helper' => 'The badge will be granted automatically upon completing this mission.',
                'cancel' => 'Cancel',
                'submit_create' => 'Create Mission',
                'submit_edit' => 'Save Changes',
            ],
            'guide' => [
                'title' => 'Technical Guide',
                'types_title' => 'Mission Types',
                'types' => [
                    'weekly' => 'Reset every week. Ideal for recurring activity.',
                    'level_up' => 'Unique missions to reach certain difficult milestones.',
                    'parallel' => 'Always active, can be completed at any time.',
                ],
                'actions_title' => 'Common Actions (Slugs)',
                'actions' => [
                    'stream_watched' => 'Watch stream (per minute)',
                    'chat_message_sent' => 'Send messages in chat',
                    'tip_sent' => 'Send tips (tokens)',
                    'subscription_purchased' => 'Subscribe to a profile',
                    'profile_updated' => 'Complete profile update',
                    'photo_uploaded' => 'Upload photos (Models Only)',
                ],
                'tips_title' => 'Tips',
                'tips_text' => 'Make sure the <strong>Required Amount</strong> is achievable for the selected time period. For weekly missions, estimate a 7-day effort.',
            ],
        ],
        'badges' => [
            'index' => [
                'title' => 'Badges Management',
                'title_header' => 'System Badges',
                'subtitle' => 'Manage the special distinctions and unique achievements of the community.',
                'create_btn' => 'New Badge',
                'filters' => [
                    'all' => 'All',
                    'hall_of_fame' => 'Hall of Fame',
                    'event' => 'Events',
                    'milestone' => 'Milestones',
                    'special' => 'Specials',
                ],
                'table' => [
                    'icon' => 'Icon',
                    'badge' => 'Badge',
                    'description' => 'Description',
                    'category' => 'Category',
                    'status' => 'Status',
                    'users' => 'Users',
                    'actions' => 'Actions',
                    'high_rarity' => 'HIGH RARITY',
                    'active' => 'Active',
                    'inactive' => 'Inactive',
                    'no_badges' => 'No badges found.',
                    'deactivate' => 'Deactivate',
                    'activate' => 'Activate',
                    'edit' => 'Edit',
                    'delete' => 'Delete',
                ],
                'delete_alert' => [
                    'title' => 'Delete this badge?',
                    'text' => 'This action cannot be undone.',
                    'confirm' => 'Yes, delete',
                    'cancel' => 'Cancel',
                ],
            ],
            'create' => [
                'title' => 'New Badge',
                'subtitle' => 'Define the visual attributes and rules for this achievement.',
            ],
            'edit' => [
                'title' => 'Edit Badge',
                'subtitle' => 'Modifying appearance and rules of: ":name"',
            ],
            'form' => [
                'preview_name' => 'Badge Name',
                'name' => 'Name',
                'name_placeholder' => 'Ex: Elite Streamer',
                'icon' => 'Icon (Font Awesome)',
                'icon_placeholder' => 'fa-crown',
                'color' => 'Main Color',
                'category' => 'Category',
                'categories' => [
                    'milestone' => 'Milestone (Progression)',
                    'hall_of_fame' => 'Hall of Fame',
                    'event' => 'Special Event',
                    'special' => 'Unique / Manual',
                ],
                'description' => 'Description',
                'description_placeholder' => 'Briefly describe this achievement...',
                'requirements' => 'Technical Requirements (JSON)',
                'req_key' => 'Key (e.g., followers)',
                'req_val' => 'Value (e.g., 1000)',
                'req_key_placeholder' => 'Key',
                'req_val_placeholder' => 'Value',
                'add_req' => 'Add Parameter',
                'active_now' => 'Activate immediately',
                'is_active' => 'Badge Active',
                'cancel' => 'Cancel',
                'submit_create' => 'Create Badge',
                'submit_edit' => 'Save Changes',
            ],
        ],
    ],

    'layout' => [
        'app' => [
            'toastr_success' => 'Success',
            'toastr_error' => 'Error',
            'toastr_warning' => 'Warning',
            'toastr_info' => 'Information',
        ],
    ],

    'logs' => [
        'title' => 'System Logs',
        'breadcrumb' => 'Audit Logs',
        'title_header' => 'System Records',
        'subtitle' => 'Complete security audit and access tracking.',
        
        'filters' => [
            'all' => 'All',
            'errors' => 'Errors',
            'warnings' => 'Warnings',
            'info' => 'Info',
            'search' => 'Search ID, IP or user...',
        ],
        
        'table' => [
            'severity' => 'Severity',
            'message_event' => 'Message and Event',
            'user' => 'Responsible User',
            'ip' => 'Origin (IP)',
            'date' => 'Date',
            'actions' => 'Actions',
            'guest' => 'System / Guest',
            'view_payload' => 'View Payload',
            'copy_id' => 'Copy ID',
            'empty' => 'No recent audit records.',
        ],

        'modal' => [
            'title' => 'Log Detail',
            'message' => 'Message',
            'payload' => 'Payload / Data',
            'close' => 'Close',
        ],
    ],

    'messages' => [
        'title' => 'Message Moderation',
        'breadcrumb' => 'Messages',
        'subtitle' => 'Moderate messages between users',
        
        'stats' => [
            'total' => 'Total Messages',
            'flagged' => 'Flagged Messages',
            'today' => 'Today',
        ],
        
        'filters' => [
            'search' => 'Search content...',
            'all_users' => 'All users',
            'all' => 'All',
            'flagged' => 'Flagged',
            'normal' => 'Normal',
            'filter_btn' => 'Filter',
        ],
        
        'table' => [
            'from' => 'From',
            'to' => 'To',
            'message' => 'Message',
            'status' => 'Status',
            'date' => 'Date',
            'actions' => 'Actions',
            'flagged' => 'Flagged',
            'normal' => 'Normal',
            'unflag' => 'Unflag',
            'flag' => 'Flag',
            'delete' => 'Delete',
            'delete_confirm' => 'Delete this message?',
            'empty' => 'No messages recorded',
        ],
    ],

    'models-2' => [
        'index' => [
            'title' => 'Models Management',
            'breadcrumb' => 'Models',
            'subtitle' => 'Moderate creators, verify profiles and monitor activity',
            
            'filters' => [
                'all' => 'All',
                'pending' => 'Pending',
                'verified' => 'Verified',
                'search' => 'Search by name or email...',
            ],
            
            'table' => [
                'model' => 'Model',
                'status_verification' => 'Status / Verification',
                'registration' => 'Registration',
                'actions' => 'Actions',
                'live' => '🔴 Live',
                
                'status' => [
                    'pending' => 'Pending',
                    'under_review' => 'Under Review',
                    'approved' => 'Verified',
                    'rejected' => 'Rejected',
                    'default' => 'Pending',
                ],
                
                'view_profile' => 'View Public Profile',
                'view_details' => 'View Details',
            ],
            
            'empty' => [
                'title' => 'No models found',
                'subtitle' => 'No creators registered that match the search criteria.',
                'clear_filters' => 'Clear filters',
            ],
        ],
        'show' => [
            'title' => 'Model Details',
            'role' => 'Model',
            
            'info' => [
                'status' => 'Status',
                'active' => 'Active',
                'suspended' => 'Suspended',
                'verification' => 'Verification',
                'member_since' => 'Member Since',
                'last_activity' => 'Last Activity',
                'stream_status' => 'Stream Status',
                'live' => 'Live',
                'back_to_list' => 'Back to list',
            ],
            
            'stats' => [
                'title' => 'Model Statistics',
                'subscribers' => 'Subscribers',
                'total_earnings' => 'Total Earnings',
                'content' => 'Content',
            ],
            
            'verification' => [
                'title' => 'Verification Status',
                'review' => 'Review Verification',
                'notes' => 'Notes:',
            ],
            
            'content_summary' => [
                'title' => 'Content Summary',
                'photos' => 'Photos',
                'videos' => 'Videos',
                'total_streams' => 'Total Streams',
                'tips_received' => 'Tips Received',
            ],
        ],
    ],

    'reports' => [
        'title' => 'Reports Management',
        'breadcrumb' => 'Reports',
        'subtitle' => 'Moderate and ensure community quality by resolving conflicts.',
        
        'stats' => [
            'total' => 'Total Reports',
            'pending' => 'Pending',
            'resolved' => 'Resolved',
            'dismissed' => 'Dismissed',
        ],
        
        'filters' => [
            'all' => 'All',
            'pending' => 'Pending',
            'resolved' => 'Resolved',
            'dismissed' => 'Dismissed',
            'search' => 'Search user or ID...',
        ],
        
        'table' => [
            'reported_by' => 'Reported By',
            'reported_item' => 'Reported Item',
            'type' => 'Type',
            'reason' => 'Reason',
            'status' => 'Status',
            'date' => 'Date',
            'actions' => 'Actions',
            'deleted_content' => 'Deleted Content',
            'view_details' => 'View Details',
            'resolve' => 'Resolve',
            'dismiss' => 'Dismiss',
            'empty' => 'No reports match the search.',
        ],

        'modal' => [
            'title' => 'Report Detail',
            'reported_by' => 'Reported By',
            'reporter_user' => 'Reporting User',
            'reported_content_user' => 'Reported Content / User',
            'reason_title' => 'REASON FOR REPORT',
            'close' => 'Close',
            'deleted' => 'Deleted',
            'unknown' => 'Unknown',
            'no_reason' => 'No reason specified',
        ],

        'exports' => [
            'title' => 'Report Export',
            'subtitle' => 'Select the dataset you want to download in CSV format.',
            'users' => [
                'label' => 'Users',
                'desc' => 'Complete database of fans and models with KYC verification status.',
            ],
            'transactions' => [
                'label' => 'Transactions',
                'desc' => 'Token purchase history, payment methods, and financial statuses.',
            ],
            'withdrawals' => [
                'label' => 'Settlements',
                'desc' => 'Report of processed withdrawals for models and pending requests.',
            ],
            'streams' => [
                'label' => 'Stream Activity',
                'desc' => 'Airtime metrics, peak viewership, and total tokens generated.',
            ],
            'subscriptions' => [
                'label' => 'Subscriptions',
                'desc' => 'List of active memberships, subscribed fans, and beneficiary models.',
            ],
            'download' => 'Download CSV',
            'info_box' => [
                'title' => 'Information:',
                'text' => 'Exported files use the UTF-8 standard. If you open the file in Microsoft Excel and see strange characters, use the "Get data from text/CSV" option and select the file origin 65001: Unicode (UTF-8).',
            ],
        ],
    ],

    'settings' => [
        'title' => 'Platform Settings',
        'breadcrumb' => 'Settings',
        'header_title' => 'System Settings',
        'header_subtitle' => 'Manage global platform parameters, payment preferences, and security.',
        
        'nav' => [
            'general' => 'General',
            'finance' => 'Finance',
            'media' => 'Media',
            'security' => 'Security',
        ],
        
        'general' => [
            'title' => 'Identity & System',
            'desc' => 'Basic brand and accessibility settings.',
            'site_name' => 'Platform Name',
            'default_locale' => 'Default Global Language',
            'locales' => [
                'es' => 'Spanish',
                'en' => 'English',
                'pt_BR' => 'Portuguese (Brazil)',
            ],
            'locale_help' => 'Default language for non-logged-in users or those without a preference.',
            'seo_desc' => 'SEO Description (Meta)',
            'maintenance_mode' => 'Maintenance Mode',
            'maintenance_mode_desc' => 'Temporarily disable public access.',
        ],
        
        'finance' => [
            'title' => 'Economy & Payments',
            'desc' => 'Business rules, commissions, and exchange rates.',
            'commission_rate' => 'Platform Commission (%)',
            'min_withdrawal' => 'Minimum Withdrawal (USD)',
            'token_value' => 'Token Value (USD)',
            'token_help' => 'Defines how much 1 token is worth in US dollars for users.',
        ],
        
        'media' => [
            'title' => 'Media & Streaming',
            'desc' => 'Video quality and storage limits.',
            'stream_quality' => 'Default Streaming Quality',
            'qualities' => [
                'sd' => 'SD (480p)',
                'hd' => 'HD (720p)',
                'fhd' => 'Full HD (1080p)',
                '4k' => 'Ultra HD (4K)',
            ],
            'upload_limit' => 'Upload Limit (MB)',
        ],
        
        'security' => [
            'title' => 'Security & Access',
            'desc' => 'Registration and verification controls.',
            'allow_registrations' => 'Allow New Registrations',
            'allow_registrations_desc' => 'Users can freely create accounts.',
            'email_verification' => 'Email Verification Required',
            'email_verification_desc' => 'Mandatory to access platform features.',
        ],
        
        'save' => [
            'unsaved' => 'You have unsaved changes',
            'button' => 'Save Changes',
        ],
    ],

    'streams' => [
        'title' => 'Manage Streams',
        'breadcrumb' => 'Streams',
        'subtitle' => 'Monitor and moderate live streams',
        'wall_button' => 'Moderation Wall',
        'list_button' => 'List View',
        
        'stats' => [
            'total' => 'Total Streams',
            'live' => 'Live',
            'ended' => 'Ended',
            'viewers' => 'Viewers',
        ],
        
        'filters' => [
            'all' => 'All',
            'live' => 'Live',
            'scheduled' => 'Scheduled',
            'ended' => 'Ended',
            'search_placeholder' => 'Search by title...',
            'filter_button' => 'Filter',
            'clear' => 'Clear filters',
        ],
        
        'badges' => [
            'live' => 'LIVE',
            'live_badge' => 'Live',
            'ended' => 'Ended',
            'scheduled' => 'Scheduled',
            'historical' => 'Historical',
        ],
        
        'actions' => [
            'view_mod' => 'View in Moderation',
            'end_stream' => 'End Stream',
            'end_confirm' => 'End this stream?',
            'end_trans' => 'End Transmission',
            'end_confirm_trans' => 'End this transmission?',
            'moderating' => 'Moderating',
            'untitled' => 'Untitled',
        ],
        
        'empty' => [
            'title' => 'No streams found',
            'desc' => 'No broadcasts matching the filters were found.',
            'mod_title' => 'No active broadcasts',
            'mod_desc' => 'There are currently no models broadcasting live.',
        ],
        
        'moderate' => [
            'title' => 'Broadcast Moderation',
            'header' => 'Moderation Wall',
            'subtitle' => 'Real-time monitoring of active broadcasts',
        ],
    ],

    'token_packages' => [
        'title' => 'Token Packages',
        'breadcrumb' => 'Token Packages',
        'create_title' => 'Create Package',
        'edit_title' => 'Edit Package',
        'create_header' => 'New Package',
        'create_subtitle' => 'Configure rewards and cost of the ticket package',
        'edit_header' => 'Edit Package',
        'edit_subtitle' => 'Update rewards and cost of the package:',
        'add_button' => 'New Package',
        
        'table' => [
            'id' => 'ID',
            'name_tokens' => 'Name / Tokens',
            'price' => 'Price (USD)',
            'bonus' => 'Bonus',
            'features' => 'Features',
            'status' => 'Status',
            'actions' => 'Actions',
        ],
        
        'features' => [
            'limited_time' => 'Limited Time',
            'expires' => 'Expires:',
            'permanent' => 'Permanent',
        ],
        
        'status' => [
            'expired' => 'Expired',
            'active' => 'Active',
            'inactive' => 'Inactive',
        ],
        
        'actions' => [
            'edit' => 'Edit',
            'delete' => 'Delete',
            'delete_confirm' => 'Are you sure you want to delete this token package?',
        ],
        
        'empty' => 'No token packages configured.',
        
        'form' => [
            'config_title' => 'Package Configuration',
            'name_label' => 'Package Name *',
            'name_placeholder' => 'Ex: Basic Package',
            'tokens_label' => 'Token Amount *',
            'bonus_label' => 'Token Bonus',
            'price_label' => 'Price (USD) *',
            
            'availability_title' => 'Availability',
            'active_label' => 'Active Package',
            'active_desc' => 'Visible to users',
            'limited_label' => 'Limited Time',
            'limited_desc' => 'Special promotion',
            'expires_label' => 'Expiration Date & Time *',
            
            'cancel' => 'Cancel',
            'create_btn' => 'Create Package',
            'update_btn' => 'Update Package',
        ],
        
        'guide' => [
            'title' => 'Commercial Guide',
            'bonus_title' => 'Bonus Strategy',
            'bonus_desc' => 'Bonuses incentivize buying larger packages. A 10% to 20% bonus is ideal to start.',
            'popular_title' => 'Popular Packages',
            'pop_1_val' => '100 Tokens',
            'pop_1_desc' => 'Starter package, ideal for testing.',
            'pop_2_val' => '1000 Tokens',
            'pop_2_desc' => 'Usually the top seller. Offers a small bonus.',
            'pop_3_val' => '5000 Tokens',
            'pop_3_desc' => 'For VIP users. The bonus must be very attractive.',
            'time_title' => 'Limited Time',
            'time_desc' => 'Use <strong>Limited Time</strong> packages during holidays (Valentine\'s Day, Christmas). These packages often offer a +50% bonus over regular packages.',
        ],
    ],

    'tokens' => [
        'title' => 'Token Management',
        'breadcrumb' => 'Tokens',
        'header' => 'Economy and Tokens',
        'subtitle' => 'Real-time audit of token flow and platform transactions.',
        
        'stats' => [
            'total_sales' => 'Total Sales',
            'purchased_desc' => 'Purchased tokens',
            'in_circulation' => 'In Circulation',
            'earned_desc' => 'Current user balance',
            'total_spent' => 'Total Spent',
            'spent_desc' => 'Consumed tokens',
            'active_users' => 'Active Users',
            'users_desc' => 'Economy participants',
        ],
        
        'filters' => [
            'all' => 'All',
            'purchases' => 'Purchases 💰',
            'spent' => 'Spent 🛒',
            'earned' => 'Earned 📈',
            'refund' => 'Refunds ↩️',
        ],
        
        'table' => [
            'title' => 'Transaction Log',
            'user' => 'User',
            'type' => 'Type',
            'amount' => 'Amount',
            'concept' => 'Concept',
            'date' => 'Date',
            'deleted_user' => 'Deleted User',
            'internal_movement' => 'Internal movement',
            'empty' => 'No transactions recorded.',
        ],
        
        'leaderboard' => [
            'title' => 'Top Users',
            'user' => 'User',
            'tokens' => 'Tokens',
            'empty' => 'No data',
        ],
    ],

    'users' => [
        'title' => 'User Management',
        'breadcrumb' => 'Users',
        'header' => 'User Management',
        'subtitle' => 'Manage fans, models, and system permissions.',
        
        'search_placeholder' => 'Search by name or email...',
        'add_button' => 'Add User',
        
        'table' => [
            'user' => 'User',
            'role_level' => 'Role / Level',
            'status' => 'Status',
            'registered' => 'Registered',
            'actions' => 'Actions',
        ],
        
        'roles' => [
            'admin' => 'Admin',
            'model' => 'Model',
            'fan' => 'Fan',
        ],
        
        'status' => [
            'online' => 'Online',
            'offline' => 'Offline',
        ],
        
        'actions' => [
            'view' => 'View Profile',
            'edit' => 'Edit',
            'disable' => 'Disable',
            'enable' => 'Enable',
        ],
        
        'empty' => [
            'title' => 'No users found',
            'description' => 'Try different search terms or filters.',
            'clear' => 'Clear search',
        ],
        
        'modal' => [
            'title' => 'Confirm Action',
            'message' => 'Are you sure you want to perform this action?',
            'cancel' => 'Cancel',
            'confirm' => 'Confirm',
        ],

        'create' => [
            'title' => 'Create User',
            'breadcrumb' => 'New User',
            'header' => 'New User',
            'subtitle' => 'Configure credentials and role for the new member',
            
            'form' => [
                'name' => 'Full Name *',
                'name_placeholder' => 'First and last name',
                'email' => 'Email Address *',
                'email_placeholder' => 'email@example.com',
                'password' => 'Password *',
                'password_placeholder' => 'Minimum 8 characters',
                'password_confirm' => 'Confirm Password *',
                'password_confirm_placeholder' => 'Repeat password',
                
                'role' => 'Assign Role *',
                'role_select' => 'Select role...',
                'role_fan' => '👤 Premium Fan',
                'role_fan_desc' => '<strong>Premium Fan:</strong> Can follow models, subscribe to exclusive content, and join live chats.',
                'role_model' => '👸 Model / Creator',
                'role_model_desc' => '<strong>Model / Creator:</strong> Access to streaming tools, content management, and revenue dashboard.',
                'role_admin' => '🛡️ Administrator',
                'role_admin_desc' => '<strong>Administrator:</strong> Full system access, content moderation, and platform analytics.',
                
                'initial_config' => 'Initial Configuration',
                'activate_now' => 'Activate account immediately',
                'activate_now_desc' => 'The user will be able to access the system after creation.',
                'notice' => 'The system will automatically generate necessary structures based on the assigned role. Verify the email is correct for system notifications.',
                
                'cancel' => 'Cancel',
                'submit' => 'Create User',
            ],
            
            'tips' => [
                'security_title' => 'Security',
                'sec_1' => 'Use minimum 8 characters with symbols.',
                'sec_2' => 'Always verify the email domain.',
                'sec_3' => 'Do not reuse passwords from other users.',
                
                'roles_title' => 'Roles',
                'role_fan' => '<strong style="color:#fff;">Fan</strong> — Content consumer',
                'role_model' => '<strong style="color:#fff;">Model</strong> — Content creator',
                'role_admin' => '<strong style="color:#fff;">Admin</strong> — Full system access',
                'role_notice' => 'The role can be modified from user edit.',
                
                'shortcuts_title' => 'Quick Links',
                'link_users' => 'View all users',
                'link_models' => 'Manage models',
                'link_verification' => 'Pending verifications',
            ],
        ],

        'edit' => [
            'title' => 'Edit User',
            'breadcrumb' => 'Edit',
            'header' => 'Edit Profile',
            
            'form' => [
                'name' => 'Full Name *',
                'name_placeholder' => 'e.g. John Doe',
                'email' => 'Email Address *',
                'email_placeholder' => 'example@email.com',
                
                'role' => 'User Role *',
                'role_fan' => '👥 Fan',
                'role_model' => '👩‍💼 Model',
                'role_admin' => '👑 Administrator',
                
                'status' => 'Status',
                'user_active' => 'Active User',
                
                'password_new' => 'New Password (Optional)',
                'password_new_placeholder' => 'Leave blank to keep current',
                'password_new_help' => 'Minimum 8 characters.',
                'password_confirm' => 'Confirm Password',
                'password_confirm_placeholder' => 'Repeat new password',
                
                'cancel' => 'Cancel',
                'submit' => 'Save Changes',
            ],
        ],

        'show' => [
            'title' => 'User Details',
            
            'profile' => [
                'status' => 'Status',
                'active' => 'Active',
                'suspended' => 'Suspended',
                'member_since' => 'Member Since',
                'last_access' => 'Last Access',
                
                'actions' => [
                    'edit' => 'Edit',
                    'debug' => 'Debug',
                    'back' => 'Back to list',
                ],
            ],
            
            'stats' => [
                'title' => 'Game Statistics',
                'level' => 'Level',
                'experience' => 'Experience',
                'tickets' => 'Tickets',
                'xp_to_next_level' => '% to Level',
            ],
            
            'missions' => [
                'title' => 'Mission History',
                'completed' => 'Completed',
                'progress' => 'Progress:',
                'empty' => 'The user has not started any missions yet.',
            ],
        ],
    ],

    'verification' => [
        'index' => [
            'title' => 'Identity Verification',
            'subtitle' => 'Manage and validate models\' identities to ensure platform security',
            
            'filters' => [
                'all' => 'All',
                'pending' => 'Pending',
                'approved' => 'Approved',
                'rejected' => 'Rejected',
            ],
            
            'table' => [
                'model' => 'Model',
                'email' => 'Email',
                'status' => 'Verification Status',
                'actions' => 'Actions',
                
                'id_prefix' => 'ID: #',
                'email_verified' => 'Email verified',
                'email_unverified' => 'Email unverified',
                
                'status_approved' => 'Approved',
                'status_under_review' => 'Under Review',
                'status_rejected' => 'Rejected',
                'status_pending' => 'Pending',
                
                'action_approve_email' => 'Approve Email',
                'action_review' => 'Review Profile',
            ],
            
            'empty' => [
                'title' => 'No pending requests',
                'subtitle' => 'There are no verifications matching the selected filters.',
                'action' => 'View all records',
            ],
            
            'modal' => [
                'approve_title' => 'Approve email manually?',
                'approve_desc' => 'This action will mark the user\'s email as verified.',
                'confirm' => 'Yes, approve',
                'cancel' => 'Cancel',
            ],
        ],

        'show' => [
            'title' => 'Identity Review',
            'subtitle' => 'Validate documents to grant the verification badge',
            'breadcrumb' => 'Detail',
            
            'profile' => [
                'id' => 'ID: #',
                'email' => 'Email: ',
                'email_verified' => 'Email Verified',
                'email_unverified' => 'Email Unverified',
                
                'legal_name' => 'Legal Name',
                'country' => 'Country',
                'age' => 'Age (Birth)',
                'years' => 'years',
                'id_document' => 'ID Document',
                'registered_at' => 'Registration Date',
                'not_provided' => '—',
            ],
            
            'documents' => [
                'title' => 'Attached Documents',
                'front' => 'FRONT OF DOCUMENT',
                'back' => 'BACK OF DOCUMENT',
                'selfie' => 'VIP SELFIE W/ ID',
                'empty' => 'No identity documents have been uploaded.',
            ],
            
            'resolution' => [
                'title' => 'Resolution',
                'notes_label' => 'Additional Notes (Optional)',
                'notes_placeholder' => 'Notes visible only to administrators...',
                'btn_approve' => 'APPROVE PROFILE',
                
                'reject_reason_label' => 'Rejection Reason (Required)',
                'reject_reason_placeholder' => 'Explain why it is rejected...',
                'btn_reject' => 'REJECT REQUEST',
                'confirm_reject' => 'Confirm rejection?',
                
                'verified_desc' => 'This profile has already been reviewed and approved.',
            ],
        ],
    ],

    'withdrawals' => [
        'index' => [
            'title' => 'Model Payouts',
            'subtitle' => 'Centralized financial management for withdrawals and payouts.',
            'breadcrumb' => 'Withdrawals',
            
            'stats' => [
                'pending' => 'Pending Approval',
                'pending_amount' => 'tokens',
                'processed_today' => 'Processed Today',
                'processed_today_desc' => 'Completed transactions',
                'total_processed' => 'Total Tokens Processed',
                'total_processed_desc' => 'Successfully converted tokens',
            ],
            
            'filters' => [
                'all' => 'All',
                'pending' => 'Pending',
                'completed' => 'Completed',
                'rejected' => 'Rejected',
            ],
            
            'table' => [
                'model' => 'Model',
                'tokens' => 'Tokens',
                'net' => 'Net (Tokens)',
                'method' => 'Method',
                'status' => 'Status',
                'date' => 'Date',
                'actions' => 'Actions',
                
                'deleted_user' => 'Deleted User',
                'empty' => 'There are no withdrawal requests.',
                
                'action_view' => 'View Details',
                'action_approve' => 'Approve',
                'action_reject' => 'Reject',
            ],
            
            'modal' => [
                'approve_title' => 'Approve Payment',
                'approve_desc' => 'You are about to approve the token conversion for',
                'approve_requested' => 'Requested Tokens',
                'approve_net' => 'Net after commission:',
                'confirm_approve' => 'Confirm Payment',
                
                'reject_title' => 'Reject Request',
                'reject_reason_label' => 'Rejection reason',
                'reject_reason_placeholder' => 'Explain the reason...',
                'confirm_reject' => 'Reject',
                
                'cancel' => 'Cancel',
            ],
        ],

        'show' => [
            'title' => 'Withdrawal Detail #',
            'subtitle' => 'Complete information of the withdrawal request',
            'breadcrumb' => 'Withdrawal #',
            
            'info' => [
                'title' => 'Withdrawal Information',
                'status' => 'Status:',
                'model' => 'Model:',
                'requested_amount' => 'Requested Amount:',
                'fee' => 'Fee:',
                'net_amount' => 'Net Amount:',
                'payment_method' => 'Payment Method:',
                'notes' => 'Notes:',
                'reject_reason' => 'Rejection Reason:',
            ],
            
            'status' => [
                'pending' => 'PENDING',
                'processing' => 'PROCESSING',
                'completed' => 'COMPLETED',
                'rejected' => 'REJECTED',
                'cancelled' => 'CANCELLED',
            ],
            
            'payment_details' => [
                'title' => 'Payment Details',
                'bank' => 'Bank:',
                'account_holder' => 'Account Holder:',
                'account_number' => 'Account Number:',
                'swift' => 'SWIFT/BIC:',
                'paypal_email' => 'PayPal Email:',
                'stripe_account' => 'Stripe Account:',
                'crypto_type' => 'Cryptocurrency:',
                'wallet_address' => 'Wallet Address:',
                'empty' => 'No payment details available',
            ],
            
            'dates' => [
                'title' => 'Dates',
                'requested' => 'Requested:',
                'processed' => 'Processed:',
            ],
            
            'actions' => [
                'title' => 'Actions',
                'approve' => 'Approve Withdrawal',
                'reject' => 'Reject Withdrawal',
                'back' => 'Back to List',
            ],
            
            'modal' => [
                'approve_title' => 'Approve Withdrawal #',
                'approve_desc' => 'Are you sure you want to approve this withdrawal?',
                'approve_model' => 'Model:',
                'approve_amount' => 'Amount:',
                'approve_net' => 'Net:',
                'approve_method' => 'Method:',
                'btn_cancel' => 'Cancel',
                'btn_approve' => 'Approve Withdrawal',
                
                'reject_title' => 'Reject Withdrawal #',
                'reject_reason_label' => 'Rejection Reason *',
                'reject_reason_placeholder' => 'Explain why this withdrawal is rejected...',
                'btn_reject' => 'Reject Withdrawal',
            ],
        ],
    ],

    'gamification' => [
        'xp_settings' => [
            'title' => 'Global XP Settings',
            'subtitle' => 'Define the XP models receive for each automatic system action.',
            'breadcrumb' => 'XP Settings',
            'breadcrumb_parent' => 'Gamification',
            
            'fans' => [
                'title' => 'XP per Action — Fans',
                'tokens_purchased' => 'Token Purchase (100%)',
                'tokens_purchased_desc' => 'Ratio to convert purchased tokens to XP (Ex: if you set 10, every 10 tokens purchased reward 10 XP; i.e. 1:1)',
                
                'tip_sent' => 'Send Tips (100%)',
                'tip_sent_desc' => 'Ratio to convert donated tokens to XP (Ex: if you set 10, sending a tip of 10 adds 10 XP)',
                
                'subscription' => 'Subscribe to a Model',
                'subscription_desc' => 'Fixed XP the Fan receives each time they purchase a subscription to a model.',
                
                'chat_message' => 'Send Chat Message',
                'chat_message_desc' => 'Fixed XP the Fan receives for sending messages.',
                
                'stream_view' => 'Join a Stream',
                'stream_view_desc' => 'Fixed XP for joining a model\'s stream.',
            ],
            
            'models' => [
                'title' => 'XP per Action — Models',
                'tip_received' => 'Receive Tips (10%)',
                'tip_received_desc' => '% of the total tip converted to XP (Ex: if you set 10, and they receive a 100 tip, they earn 10 XP)',
                
                'new_subscriber' => 'New Subscriber',
                'new_subscriber_desc' => 'Fixed XP the model receives each time they gain a new subscriber.',
                
                'chat_message' => 'Receive Chat Message',
                'chat_message_desc' => 'Fixed XP for each message fans send them in chat.',
                
                'stream_view' => 'Stream Viewer',
                'stream_view_desc' => 'Fixed XP for each fan viewing/entering their stream.',
            ],
            
            
            'units' => [
                'base_percent' => 'base %',
                'fixed_xp' => 'Fixed XP',
                'reward_percent' => 'reward %',
            ],
            
            'save' => 'Save Changes',
            
            'note' => 'Note:',
            'note_desc' => 'Changes apply immediately for future events. Past actions are not recalculated. The <em>chat</em> and <em>stream_view</em> events must be triggered to the listener for these values to take effect.',
        ],
    ],

    'flash' => [
        'users' => [
            'email_approved'       => 'Email manually approved.',
            'verification_sent'    => 'Verification email resent successfully.',
            'verification_testing' => 'Testing mode: email sending will be enabled in production.',
            'already_verified'     => 'This user already has their email verified.',
            'created'              => 'User created successfully.',
            'updated'              => 'User updated successfully.',
            'cannot_delete_self'   => 'You cannot delete your own account.',
            'deleted'              => 'User deleted successfully.',
            'status_updated'       => 'Status updated successfully.',
        ],
        'content' => [
            'photo_approved'  => 'Photo approved successfully.',
            'photo_rejected'  => 'Photo rejected.',
            'photo_deleted'   => 'Photo deleted successfully.',
            'video_approved'  => 'Video approved successfully.',
            'video_rejected'  => 'Video rejected.',
            'video_deleted'   => 'Video deleted successfully.',
            'photos_approved' => ':count photos approved.',
            'photos_rejected' => ':count photos rejected.',
        ],
        'verification' => [
            'already_approved'  => 'This profile has already been approved.',
            'profile_approved'  => 'Profile of :name approved successfully.',
            'profile_rejected'  => 'Profile of :name rejected. The user has been notified.',
            'profile_in_review' => 'Profile of :name placed under review.',
        ],
        'withdrawals' => [
            'only_pending_approve' => 'Only pending withdrawals can be approved.',
            'approved'             => 'Withdrawal approved successfully.',
            'only_pending_reject'  => 'Only pending withdrawals can be rejected.',
            'rejected'             => 'Withdrawal rejected.',
        ],
        'achievements' => [
            'created'       => 'Achievement created successfully.',
            'updated'       => 'Achievement updated successfully.',
            'cannot_delete' => 'This achievement cannot be deleted because it has already been unlocked by users.',
            'deleted'       => 'Achievement deleted successfully.',
            'activated'     => 'Achievement activated successfully.',
            'deactivated'   => 'Achievement deactivated successfully.',
        ],
        'missions' => [
            'created'       => 'Mission created successfully.',
            'updated'       => 'Mission updated successfully.',
            'cannot_delete' => 'This mission cannot be deleted because it has already been assigned to users.',
            'deleted'       => 'Mission deleted successfully.',
            'activated'     => 'Mission activated successfully.',
            'deactivated'   => 'Mission deactivated successfully.',
        ],
        'levels' => [
            'created' => 'Level created successfully.',
            'updated' => 'Level updated successfully.',
            'deleted' => 'Level deleted successfully.',
        ],
        'badges' => [
            'created'        => 'Badge created successfully.',
            'updated'        => 'Badge updated successfully.',
            'cannot_delete'  => 'This badge cannot be deleted because it has already been granted.',
            'deleted'        => 'Badge deleted successfully.',
            'status_updated' => 'Badge status updated.',
        ],
        'token_packages' => [
            'created' => 'Token package created successfully.',
            'updated' => 'Token package updated successfully.',
            'deleted' => 'Token package deleted successfully.',
        ],
        'settings' => [
            'updated'    => 'Settings updated successfully.',
            'xp_updated' => 'Global XP settings updated successfully.',
        ],
        'streams' => [
            'ended'      => 'Stream ended successfully.',
            'not_active' => 'The stream is no longer active.',
        ],
        'reports' => [
            'resolved'  => 'Report resolved successfully.',
            'dismissed' => 'Report dismissed.',
        ],
        'messages' => [
            'deleted'      => 'Message deleted successfully.',
            'flag_updated' => 'Message status updated.',
        ],
        'auth' => [
            'register_model_success' => 'Registration successful! Please verify your email before continuing.',
            'default_bio'            => 'New model on the platform.',
        ],
        'fan' => [
            'access_denied'             => 'Access denied.',
            'not_a_model'               => 'The user is not a model.',
            'invalid_content_type'      => 'Invalid content type.',
            'invalid_data'              => 'Invalid data.',
            'favorite_added'            => 'Added to favorites',
            'favorite_removed'          => 'Removed from favorites',
            'favorite_error'            => 'Error updating favorites.',
            'notification_read'         => 'Notification marked as read',
            'notification_read_error'   => 'Error marking the notification.',
            'notifications_all_read'    => 'All notifications marked as read',
            'notifications_read_error'  => 'Error marking the notifications.',
            'wrong_password'            => 'The current password is incorrect.',
            'invalid_profile_data'      => 'Invalid data.',
            'profile_updated'           => 'Profile updated successfully.',
            'profile_update_error'      => 'Error updating the profile.',
            'already_subscribed'        => 'You are already subscribed to this model.',
            'insufficient_tokens'       => 'Insufficient tokens.',
            'subscription_success'      => 'Subscription successful',
            'subscription_error'        => 'Error processing the subscription.',
            'subscription_cancelled'    => 'Subscription cancelled successfully',
            'subscription_cancel_error' => 'Error cancelling the subscription.',
            'sub_tx_fan'                => 'Monthly subscription to :name',
            'sub_tx_model'              => 'Monthly subscription from :name',
            'invalid_package'           => 'Invalid or outdated token package.',
            'invalid_price'             => 'The selected price or package is not valid.',
            'recharge_success'          => 'Recharge successful',
            'recharge_error'            => 'Error processing the recharge. Please try again.',
            'recharge_tx'               => 'Quick recharge of :count tokens',
            'purchase_success'          => 'Purchase successful',
            'purchase_tx'               => 'Purchase of :total tokens (:base + bonus)',
        ],
        'benefits' => [
            'chat'        => 'Chat enabled',
            'cashback_5'  => '5% Cashback on tips',
            'invisible'   => 'Invisible Mode',
            'vip'         => '10% Cashback + VIP Priority',
            'elite'       => 'Total Elite Access',
            'default_league' => 'Gray',
        ],
        'achievements' => [
            'first_tip_name'       => 'First Tip',
            'first_tip_desc'       => 'Send your first tip',
            'generous_name'        => 'Generous',
            'generous_desc'        => 'Send 100 tips',
            'vip_subscriber_name'  => 'VIP Subscriber',
            'vip_subscriber_desc'  => 'Maintain 5 active subscriptions',
            'climber_name'         => 'Climber',
            'climber_desc'         => 'Reach level 10',
            'legend_name'          => 'Legend',
            'legend_desc'          => 'Reach level 21',
        ],
        'model' => [
            'profile_required'           => 'You need an approved profile to access :section.',
            'rejected_flash'             => 'Your profile was rejected. Reason: :reason. You can correct the information and resubmit.',
            'under_review_flash'         => 'Your profile is under review. We will notify you by email when it is approved.',
            'under_review_no_edit'       => 'Your profile is under review. You cannot modify it until you receive a response.',
            'edit_blocked_review'        => 'You cannot edit your profile while it is under review.',
            'edit_blocked_rejected'      => 'Your profile was rejected. Use the onboarding process to correct the information.',
            'settings_approved_required' => 'You need an approved profile to access settings.',
            'settings_updated'           => 'Settings updated successfully.',
            'profile_updated'            => 'Profile updated successfully.',
            'profile_updated_approved'   => 'Profile updated successfully. Photo changes require new approval.',
            'default_bio'                => 'New model on the platform',
            'analytics_required'         => 'You need an approved profile to access analytics.',
            'earnings_required'          => 'You need an approved profile to access earnings.',
            'leaderboard_required'       => 'You need an approved profile to access the ranking.',
            'missions_required'          => 'You need an approved profile to access missions.',
            'achievements_required'      => 'You need an approved profile to access achievements.',
            'not_authorized'             => 'Unauthorized',
            'access_denied'              => 'Access denied.',
            'notification_read'          => 'Notification marked as read',
            'notification_read_error'    => 'Error marking the notification.',
            'notifications_all_read'     => 'All notifications marked as read',
            'notifications_read_error'   => 'Error marking the notifications.',
            'mission_not_found'          => 'Mission not found.',
            'mission_already_claimed'    => 'This mission has already been claimed.',
            'mission_not_complete'       => 'You have not completed this mission yet.',
            'mission_reward_claimed'     => 'Reward claimed successfully!',
            'default_fan_name'           => 'User',
        ],
        'onboarding' => [
            'step1_success'         => 'Step 1 completed. Now upload your ID.',
            'step2_success'         => 'Documents uploaded successfully. Last step.',
            'step3_success'         => 'Profile submitted for review. We will notify you when it is approved.',
            'complete_prev_steps'   => 'You must complete all previous steps.',
            'profile_not_found'     => 'Profile not found. Please complete step 1 first.',
            'docs_required'         => 'All required documents (Front, Back, Selfie) are required.',
            'invalid_files'         => 'The uploaded files are not valid. Please try again.',
            'upload_error'          => 'Error uploading documents. Please try again.',
            'unexpected_error'      => 'Unexpected error: :message',
        ],
        'photo' => [
            'max_photos'   => 'You cannot upload more than 10 photos at once.',
            'invalid_mime' => 'The file must be a valid image (jpeg, png, jpg, gif, webp, svg, bmp, tiff).',
            'max_size'     => 'Each photo must not exceed 10MB.',
            'uploaded_one' => 'Photo uploaded successfully.',
            'uploaded_many'=> ':count photos uploaded successfully.',
            'deleted'      => 'Photo deleted successfully.',
        ],
        'video' => [
            'max_size'     => 'The selected video exceeds the 50MB maximum limit.',
            'invalid_mime' => 'The video must be in MP4, MOV, AVI or WMV format.',
            'thumb_max'    => 'The thumbnail must not exceed 5MB.',
            'uploaded'     => 'Video uploaded successfully.',
            'deleted'      => 'Video deleted successfully.',
        ],
        'stream' => [
            'active_warning'     => 'You have :count active stream(s): :titles. They will be automatically ended when you create the new stream.',
            'started'            => 'Stream started successfully! Configure OBS with your stream key and start broadcasting.',
            'paused'             => 'Stream paused.',
            'resumed'            => 'Stream resumed.',
            'ended'              => 'Stream ended successfully.',
            'deleted'            => 'Stream deleted successfully.',
            'settings_updated'   => 'Stream settings updated.',
            'not_live'           => 'The stream is not active. Configure OBS first.',
            'action_completed'   => 'Action marked as completed',
            'message_sent'       => 'Message sent',
            'private_chat_label' => 'Private Chat',
        ],
        'withdrawal' => [
            'tx_description' => 'Withdrawal request via :method',
            'request_sent'   => 'Withdrawal request submitted successfully.',
            'cancel_error'   => 'You can only cancel pending withdrawals.',
            'cancelled'      => 'Withdrawal cancelled successfully.',
        ],
        'notification' => [
            'all_read'    => 'All notifications marked as read',
            'all_deleted' => 'All notifications deleted',
        ],
        'payment' => [
            'failed_default' => 'The payment could not be processed',
        ],
        'profile_public' => [
            'login_required'            => 'You must log in to subscribe.',
            'model_not_found'           => 'Model not found.',
            'fans_only'                 => 'Only fans can subscribe to models.',
            'no_self_subscribe'         => 'You cannot subscribe to your own profile.',
            'already_subscribed'        => 'You already have an active :tier subscription to this model.',
            'insufficient_tokens'       => 'You do not have enough tokens for this subscription.',
            'subscribe_success'         => ':tier subscription activated successfully for :amount tokens! You now have exclusive access to :name.',
            'subscribe_error'           => 'An error occurred while processing your subscription. Please try again.',
            'login_required_short'      => 'You must log in.',
            'insufficient_tokens_short' => 'You do not have enough tokens.',
            'tip_success'               => 'Tip sent successfully!',
            'tip_error'                 => 'Error processing the tip.',
            'roulette_success'          => 'You spun the roulette!',
            'roulette_error'            => 'Error processing the spin.',
            'chat_fans_only'            => 'Only fans or the model can chat.',
            'chat_insufficient_tokens'  => 'Insufficient tokens',
            'tx_subscribe_fan'          => ':tier Subscription to :name',
            'tx_subscribe_model'        => ':tier Subscription from :name',
            'tx_tip_fan'                => 'Tip sent to :name:menu',
            'tx_tip_model'              => 'Tip received from :name:action',
            'tx_tip_menu_suffix'        => ' (Menu)',
            'tx_tip_action_suffix'      => ' - Menu Action',
            'tx_roulette_fan'           => 'Roulette spin in :name room',
            'tx_roulette_model'         => 'Roulette spin from :name',
            'tx_chat_fan'               => 'Private chat unlock with :name (:hours h)',
            'tx_chat_model'             => 'Private chat unlock from :name (:hours h)',
        ],
        'report' => [
            'no_self_report' => 'You cannot report yourself.',
            'sent'           => 'Report submitted successfully. Thank you for helping us maintain safety.',
            'error'          => 'An error occurred while sending the report. Please try again.',
        ],
        'rtmp' => [
            'key_live_error' => 'You cannot regenerate your key while you are live. End your broadcast first.',
            'key_generated'  => 'Stream key generated successfully',
        ],
        'streaming' => [
            'not_active'   => 'Stream is not active',
            'unauthorized' => 'Unauthorized',
            'started'      => 'Broadcast started',
            'stopped'      => 'Broadcast ended',
            'connected'    => 'Connected to stream',
            'disconnected' => 'Disconnected from stream',
        ],
        'stream_view' => [
            'not_active'          => 'This stream is not active.',
            'subscribe_required'  => 'You need to subscribe to view this stream.',
            'insufficient_tokens' => 'You do not have enough tokens. You have :count tokens available.',
            'tip_error'           => 'Error sending the tip. Please try again.',
            'tx_tip_fan'          => 'Tip in stream ":title" to :name',
            'tx_tip_model'        => 'Tip in stream ":title" from :name',
        ],
        'middleware' => [
            'onboarding_required'   => 'Complete your verification process to access.',
            'subscription_required' => 'You need an active subscription to access this content.',
            'role_denied'           => 'You do not have permission to access this section.',
            'verified_denied'       => 'Access denied.',
            'profile_incomplete'    => 'You must complete your profile first.',
            'profile_pending'       => 'This feature will be available when your profile is approved.',
        ],
    ],
    
    'models' => [
        'profile' => [
            'not_specified' => 'Not specified',
            'height'        => 'Height',
            'weight'        => 'Weight',
            'measurements'  => 'Measurements',
            'years_old'     => 'years old',
            'social_networks' => [
                'instagram' => 'Instagram',
                'twitter'   => 'Twitter',
                'tiktok'    => 'TikTok',
                'facebook'  => 'Facebook',
                'youtube'   => 'YouTube',
                'onlyfans'  => 'OnlyFans',
            ],
            'body_types' => [
                'Delgado'       => '🌸 Slim',
                'Atlético'      => '💪 Athletic',
                'Talla mediana' => '🌺 Medium Build',
                'Con curvas'    => '🍑 Curvy',
                'BBW'           => '👸 BBW',
            ],
            'ethnicities' => [
                'Blanca'      => '🤍 White',
                'Latina'      => '🌹 Latina',
                'Asiática'    => '🌸 Asian',
                'Árabe'       => '🌙 Arab',
                'Negra'       => '🖤 Black',
                'India'       => '🪷 Indian',
                'Multiétnica' => '🌈 Multi-ethnic',
            ],
            'hair_colors' => [
                'Rubio'      => '👱‍♀️ Blonde',
                'Moreno'     => '👩‍🦳 Brunette',
                'Pelo Negro' => '👩‍🦲 Black Hair',
                'Colorido'   => '🌈 Colorful',
                'Pelirroja'  => '👩‍🦰 Redhead',
            ],
        ],
        'user' => [
            'benefits' => [
                'reduced_commission' => [
                    'name'        => 'Reduced Commission',
                    'description' => '15% commission (previously 20%)',
                ],
                'search_priority' => [
                    'name'        => 'Search Priority',
                    'description' => 'Appears first in results',
                ],
                'vip_badge' => [
                    'name'        => 'VIP Badge',
                    'description' => 'Special badge on your profile',
                ],
                'priority_support' => [
                    'name'        => 'Priority Support',
                    'description' => '24/7 preferential attention',
                ],
            ],
            'token_benefits' => [
                'level_6'  => '5% Cashback on all tips',
                'level_16' => '10% Cashback + Priority in chat',
            ],
            'missions' => [
                'tokens' => [
                    'title'  => 'Recharge 1000 tokens',
                    'reward' => '50 XP + 10 Tickets',
                ],
                'subscription' => [
                    'title'  => 'Subscribe to 3 models',
                    'reward' => '100 XP + 20 Tickets',
                ],
                'daily_tip' => [
                    'title'       => 'Send 5 tips',
                    'description' => 'Send tips to your favorite models',
                ],
                'weekly_login' => [
                    'title'       => 'Connect 3 days this week',
                    'description' => 'Log in at least 3 different days',
                ],
                'monthly_spend' => [
                    'title'       => 'Spend 5000 tokens this month',
                    'description' => 'Use tokens on tips and subscriptions',
                ],
                'obligatory_level' => [
                    'title'       => 'Reach :xp XP',
                    'description' => 'Complete this mission to reach level :level',
                ],
                'model_weekly_photos' => [
                    'title'       => 'Upload 5 photos this week',
                    'description' => 'Share new content with your fans',
                ],
                'model_monthly_streams' => [
                    'title'       => 'Do 3 streams this month',
                    'description' => 'Connect live with your audience',
                ],
                'model_daily_tips' => [
                    'title'       => 'Receive 10 tips today',
                    'description' => 'Interact with your fans',
                ],
            ],
        ],
    ],
    
    'notifications' => [
        'achievement' => [
            'unlocked' => 'Achievement unlocked! :name',
        ],
        'badge' => [
            'earned' => 'Special badge earned! :name',
        ],
        'chat' => [
            'extended' => [
                'model_title' => 'Chat Extended',
                'model_msg'   => ':name has extended the private chat for 24 hours.',
                'model_btn'   => 'Go to Chat',
                'fan_title'   => 'Chat Extended Successfully',
                'fan_msg'     => 'You have extended the chat with :name for 24 extra hours.',
                'fan_btn'     => 'Continue Chatting',
            ],
            'unlocked' => [
                'model_title' => 'New Chat Unlocked!',
                'model_msg'   => ':name has unlocked your private chat.',
                'model_btn'   => 'Go to Chat',
                'fan_title'   => 'Chat Unlocked!',
                'fan_msg'     => 'You have unlocked the private chat with :name.',
                'fan_btn'     => 'Start Chatting',
            ],
            'new_message' => [
                'title' => 'New Private Message',
                'btn'   => 'Reply',
            ],
        ],
        'level' => [
            'up' => 'Congratulations! You reached level :level - :name',
        ],
        'model' => [
            'live_title' => 'Live Now!',
            'live_msg'   => ':name is streaming: :title',
            'live_btn'   => 'Watch Stream',
            'verify_email_subject' => 'Verify your Model account - Lustonex',
        ],
        'follower' => [
            'title' => 'New Follower!',
            'msg'   => ':name started following you',
            'btn'   => 'View Profile',
        ],
        'subscriber' => [
            'fan_title'   => 'Successful Subscription!',
            'fan_msg'     => 'You have successfully subscribed to :name\'s content',
            'fan_btn'     => 'View Profile',
            'model_title' => 'New Subscriber!',
            'model_msg'   => ':name subscribed to your content',
            'model_btn'   => 'View Subscribers',
        ],
        'payment' => [
            'success_title' => 'Payment Successful',
            'success_msg'   => 'Your purchase of :tokens tokens was processed successfully',
            'success_btn'   => 'View History',
        ],
        'tip' => [
            'received_title' => 'Tip Received!',
            'received_msg'   => ':name sent you :amount tokens',
            'received_btn'   => 'View Earnings',
        ],
        'withdrawal' => [
            'approved_title' => 'Withdrawal Approved',
            'approved_msg'   => 'Your withdrawal of $:amount has been approved and processed',
            'approved_btn'   => 'View Withdrawals',
            'rejected_title' => 'Withdrawal Rejected',
            'rejected_msg'   => 'Your withdrawal of $:amount was rejected. Reason: :reason',
            'rejected_btn'   => 'View Details',
            'not_specified'  => 'Not specified',
        ],
        'gamification' => [
            'achievement_title' => 'Achievement Unlocked!',
            'achievement_msg'   => 'You have unlocked the achievement: :name',
            'level_title'       => 'Leveled Up!',
            'level_msg'         => 'Congratulations! You reached Level :level: :name',
        ],
    ],
    
    'services' => [
        'payment' => [
            'invalid_paypal_email' => 'Invalid PayPal Email',
            'invalid_skrill_email' => 'Invalid Skrill Email',
            'processed_successfully' => 'Payment processed successfully',
            'card_declined' => 'Card declined',
            'insufficient_funds' => 'Insufficient funds',
            'unknown_error' => 'Unknown error',
            'payment_error' => 'Payment error',
            'paypal_success' => 'PayPal payment processed successfully',
            'paypal_rejected_reason' => 'Payment rejected by PayPal',
            'paypal_rejected' => 'The payment was rejected by PayPal',
            'skrill_success' => 'Skrill payment processed successfully',
            'skrill_rejected_reason' => 'Payment rejected by Skrill',
            'skrill_rejected' => 'The payment was rejected by Skrill',
            'required_field' => 'Required field: :field',
            'invalid_card_number' => 'Invalid card number',
            'invalid_cvv' => 'Invalid CVV',
            'invalid_exp_month' => 'Invalid expiration month',
            'expired_card' => 'Expired card',
            'integration_not_implemented_card' => 'Real card integration not implemented',
            'integration_not_implemented_paypal' => 'Real PayPal integration not implemented',
            'integration_not_implemented_skrill' => 'Real Skrill integration not implemented',
        ],
    ],
];
